version: "3"

services:
  db:
    container_name: mysql_db_1
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./monster-backend/mysql.init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build: ./monster-backend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  monster-admin-frontend:
    build: ./monster-admin-frontend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - server

  monster-frontend:
    build: ./monster-frontend
    restart: always
    ports:
      - 80:8000
    depends_on:
      - server
 
