import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/Navbar";
import Banner from "@/components/Banner";
import PostItem from "@/components/PostItem";
import Footer from "@/components/Footer";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const PostList = ({ posts }) => {
  // 这里需要用到grid布局，可以灵活的进行表格布局
  // 与flex布局不同的是，grid布局可以指定每个元素的宽度和高度
  // flex 只能zai主轴上进行布局, grid可以在主轴和交叉轴上进行布局
  // flex是一维布局，grid是二维布局
  return (
    <div className={styles.post_list}>
      {posts.map((item) => {
        const { id, title, author, date, imgUrl, content, tags } = item;
        return (
          <PostItem
            key={id}
            title={title}
            author={author}
            date={date}
            content={content}
            tags={tags}
            imgUrl={imgUrl}
          />
        );
      })}
    </div>
  );
};

export default function Home() {
  // 模拟下数据源
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    const getPostList = async () => {
      // 页面加载完成去请求文章列表, 如果是服务端远程要处理 cors 跨域问题
     const res = await fetch("/api/v1/posts", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      }).then((res) => res.json());
      if(+res?.code === 0) {
        setPosts(res.data);
      }
    };
    getPostList();
  }, []);

  // footer要放到main外面，因为main有内填充，footer两边没有空隙
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <Banner />
        <PostList posts={posts} />
      </main>
      <Footer />
    </>
  );
}
