### 文章管理接口

#### 新增文章
POST http://localhost:8080/api/v1/posts HTTP/1.1
Content-Type: application/json

{
    "categoryId": 2,
    "title": "生活文章标题1",
    "content": "文章内容",
    "author": "作者1"
}

#### 获取文章列表
GET http://localhost:8080/api/v1/posts HTTP/1.1
Content-Type: application/json

### 获取文章详情
GET http://localhost:8080/api/v1/posts/1 HTTP/1.1
Content-Type: application/json



#### 修改文章详情
PUT http://localhost:8080/api/v1/posts/5 HTTP/1.1
Content-Type: application/json

{
    "categoryId": 1,
    "title": "修改后的文章标题5",
    "content": "修改后的文章内容5",
    "author": "修改后的作者5"
}


#### 删除文章
DELETE http://localhost:8080/api/v1/posts/4 HTTP/1.1
Content-Type: application/json


## 用户管理

### 登陆接口
POST http://localhost:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "123455"
}

### 获取用户列表接口
GET http://localhost:3000/api/v1/users HTTP/1.1
Content-Type: application/json



### 获取文章分类列表
GET http://localhost:8080/api/v1/categories HTTP/1.1
Content-Type: application/json


### 新增分类
POST http://localhost:8080/api/v1/categories HTTP/1.1
Content-Type: application/json

{
    "name": "旅行"
}

### 更新分类
PUT  http://localhost:8080/api/v1/categories/7 HTTP/1.1
Content-Type: application/json

{
    "name": "环球"
}

### 获取分类详情
GET http://localhost:8080/api/v1/categories/2 HTTP/1.1
Content-Type: application/json


### 删除分类
DELETE  http://localhost:8080/api/v1/categories/7 HTTP/1.1
Content-Type: application/json
